CREATE TABLE IF NOT EXISTS Beers (
    Id INTEGER IDENTITY NOT NULL,
    Name VARCHAR (100),
    BrewerId INTEGER,
    CategoryId INTEGER,
    Price FLOAT,
    Stock INTEGER,
    Alcohol FLOAT,
    Version INTEGER,
    Image LONGVARBINARY,
    PRIMARY KEY (Id)
);
CREATE TABLE IF NOT EXISTS Brewers (
    Id INTEGER IDENTITY NOT NULL,
    Name VARCHAR (50),
    Address VARCHAR (50),
    ZipCode VARCHAR (6),
    City VARCHAR (50),
    Turnover INTEGER,
    PRIMARY KEY (Id)
);
CREATE TABLE IF NOT EXISTS Categories (
    Id INTEGER IDENTITY NOT NULL,
    Category VARCHAR (50),
    PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS BeerOrders (
    Id INTEGER IDENTITY NOT NULL,
    Name VARCHAR (100),
    PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS BeerOrderItems (
    Id INTEGER IDENTITY NOT NULL,
    Number INTEGER,
    BeerId INTEGER,
    BeerOrderId INTEGER,
    PRIMARY KEY (Id)
);
